export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_PENDING = 'FETCH_POST_PENDING';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';
